config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about", to: "pages#about"
  get "/about_me", to: "pages#about_me"

  get "/my_car" , to: "cars#my_car"
  get "/my_car_modle" , to: "cars#car_modle"
  get "/the_color" , to: "cars#car_color"
  get "/race_car"  ,to: "cars#car_kinde"
  get "/suv_car"  ,to: "cars#suv"
  get "/coop"  ,to: "cars#coop_car"
  get "/edit" ,to: "pages#edit_each"
  get "/info" ,to: "pages#info_page"
  get "/sign_in" ,to: "pages#sign_in"

  devise_for :users

  resources :users
  resources :books
  resources :favorites

  post "/add_book_to_favorites", to: "favorites#create"
  delete "/remove_book_from_favorites", to: "favorites#destroy"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :favorites
  has_many :favorite_books, through: :favorites, source: :book
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  
  validates :last_name, presence: true
  validate :validate_age

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def validate_age
    if age < 18
      errors.add(:dob, 'you should be older than 18 years')
    end
  end

  def age
    return 22 if dob.nil?
    
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user , only: [:show,:edit,:destroy,:update]

  def index
    @users=User.all
  end

  def show
  end

  def destroy
    @user.destroy

    redirect_to users_path
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      error_message
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      error_message
      render :edit
    end
  end

  private 

  def find_user
    @user = User.find(params[:id])
  end 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :gender, :dob, :ssn, :adress, :linkedin_profil)
  end

  def error_message
    flash.now[:alert] = "There were errors in your submission."
  end

end

app/views/users/edit.html.erb
<h1>update User</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>


  <div>
    <%= form.label "date of birth" %>
    <%= form.datetime_field :dob %>
  </div>


  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :ssn %>
    <%= form.text_field :ssn %>
  </div>

  <div>
    <%= form.label :linkedin_profil %>
    <%= form.text_field :linkedin_profil %>
  </div>

  <div>
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.submit "Update a User" %>
  </div>
<% end %>


<%= button_to 'cancel' , users_path, method: :get%>

app/views/users/index.html.erb
<% if user_signed_in? %>
 welcome: <%=current_user.first_name %><br>
 user email: <%=current_user.email %>
<% end %>

<div style="margin-bottom: 20px;">
  <%= button_to 'Create a New User', new_user_path, method: :get, class: 'btn btn-primary' %>
</div>

<div class="users-container">
  <% @users.each do |user| %>
    <div class="user-card">
      <p><strong>Full Name:</strong> <%= user.full_name %></p>
      
      <div class="user-actions">

        <%= button_to 'View User Details', "/users/#{user.id}", method: :get, class: 'btn btn-info' %>
        <%= button_to 'Update User', edit_user_path(user), method: :get, class: 'btn btn-warning' %>
        <%= button_to 'Delete User', "/users/#{user.id}", method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>


  <div>
    <%= form.label "date of birth" %>
    <%= form.datetime_field :dob %>
  </div>


  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :ssn %>
    <%= form.text_field :ssn %>
  </div>

  <div>
    <%= form.label :linkedin_profil %>
    <%= form.text_field :linkedin_profil %>
  </div>

  <div>
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.submit "Create a User" %>
  </div>
<% end %>


<%= button_to 'cancel' , users_path, method: :get%>

app/views/users/show.html.erb
<br><br><%= link_to image_tag("images.png", alt:"back",width:30,height:30),users_path%><br><br>
first_name: <%= @user.first_name %><br>
last_name: <%= @user.last_name %><br>
email : <%= @user.email%><br>
<div style="margin-bottom: 50px;">
  <%= button_to 'Create a New Book', new_book_path, method: :get, class: 'btn btn-primary' %>
</div>
<%=link_to ('user email'),users_path %><br>
gender: <%= @user.gender%><br>
age: <%= @user.age%><br>
<%= link_to ('linkedin_profil'), "https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/learn/lecture/3850390?start=1#content", target: '_blank' %><br>
ssn : <%= @user.ssn%><br>
full_name: <%= @user.full_name %><br>