config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about", to: "pages#about"
  get "/about_me", to: "pages#about_me"

  get "/my_car" , to: "cars#my_car"
  get "/my_car_modle" , to: "cars#car_modle"
  get "/the_color" , to: "cars#car_color"
  get "/race_car"  ,to: "cars#car_kinde"
  get "/suv_car"  ,to: "cars#suv"
  get "/coop"  ,to: "cars#coop_car"
  get "/edit" ,to: "pages#edit_each"
  get "/info" ,to: "pages#info_page"
  get "/sign_in" ,to: "pages#sign_in"

  devise_for :users

  resources :users
  resources :books
  resources :favorites

  post "/add_book_to_favorites", to: "favorites#create"
  delete "/remove_book_from_favorites", to: "favorites#destroy"

end

app/views/pages/about.html.erb
<%= button_to 'go to about me' , about_me_path , method: :get%>


<%= button_to 'go back home' , root_path , method: :get%>

<%= button_to 'go to my_car' , my_car_path , method: :get%>


<%= button_to 'go to car modle' , my_car_modle_path , method: :get%>
<%= button_to 'go back home' , root_path , method: :get%>


this is about page

app/views/pages/about_me.html.erb
<%= button_to 'go to about' , about_path , method: :get%>

<%= button_to 'go back home' , root_path , method: :get%>

<%= button_to 'go to my_car' , my_car_path , method: :get%>


<%= button_to 'go to car modle' , my_car_modle_path , method: :get%>


<%= button_to 'go back home' , root_path , method: :get%>

<%=@name%>
<%=@email%>

app/views/pages/edit_each.html.erb
you could edit each field here.

app/views/pages/home.html.erb
<body class="bg-light">
  <div class="container py-5">
    <!-- Page Title -->
    <h1 class="text-center mb-4">Books List</h1>
    Favorite Books: <%= current_user.favorites.count%>

    <!-- Books Display -->
    <div class="row">
      <% @all_books.each do |book| %>
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5> <%= link_to book.title, book_path(book), class: 'card-title text-primary' %></h5>

              <p class="card-text"><strong>Author Name:</strong> <%= book.user.full_name %></p>
              <p class="card-text"><strong>Books Published:</strong> <%= book.user.books.count %></p>
              <p class="card-text"><strong>Published At:</strong> <%= book.time_ago %></p>
              <% if user_signed_in? %>
                <%if book.user.id == current_user.id%>
                  <i class="fa fa-crown"></i>
                <%elsif !current_user.favorite_books.include?(book)%>
                  <%= button_to add_book_to_favorites_path(book_id:book.id), method: :post, title: 'add to favorite' do %>
                  <i class="fa fa-heart text-secondary"></i>
                  <%end%>
                <%else%>
                  <%= button_to remove_book_from_favorites_path(book_id:book.id), method: :delete, title: 'remove from favorites' do %>
                    <i class="fa fa-heart text-danger"></i>
                  <%end%>
                <%end%>
              <%end%>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <div class="d-flex justify-content-center">
    <%= paginate @all_books %>
  </div>

    <!-- Action Buttons -->
    <div class="text-center mt-4">
      <% if user_signed_in? %>
        <%= button_to 'My Favorites Books', favorites_path, method: :get, class: 'btn btn-primary' %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= button_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</body>

app/views/pages/info_page.html.erb
<%= @info%>

app/views/pages/sign_in.html.erb
<%= @login=%>
<%=@pass%>