config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about", to: "pages#about"
  get "/about_me", to: "pages#about_me"

  get "/my_car" , to: "cars#my_car"
  get "/my_car_modle" , to: "cars#car_modle"
  get "/the_color" , to: "cars#car_color"
  get "/race_car"  ,to: "cars#car_kinde"
  get "/suv_car"  ,to: "cars#suv"
  get "/coop"  ,to: "cars#coop_car"
  get "/edit" ,to: "pages#edit_each"
  get "/info" ,to: "pages#info_page"
  get "/sign_in" ,to: "pages#sign_in"

  devise_for :users

  resources :users
  resources :books
  resources :favorites

  post "/add_book_to_favorites", to: "favorites#create"
  delete "/remove_book_from_favorites", to: "favorites#destroy"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy # returns all the favorites records for the Book. For example if we Book.last.favorites, this will return all the favorites records.
  has_many :favorited_by_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :description, presence: true
  validates :book_type, presence: true
  validates :author_country, presence: true
  validates :pages, presence: true,numericality: { only_integer: true, greater_than_or_equal_to:100,less_than_or_equal_to:1000}
  validate :title_length
  validate :description_length
  validate :author_country_check
  validate :book_type_check
  # validate :book_pages


  def title_length
    if title.length < 3
      errors.add(:title, 'Title book shold be more than 3 letters')
    end
  end

  def description_length
    if description.length > 200
      errors.add(:description, "description should not be less than 200 char")
    end
  end

  def author_country_check
    allwoed_country_list=["uk","iraq","us"]
    if allwoed_country_list.exclude?(author_country)
        errors.add(:author_country,'aouther country not ecpected')
    end
  end

  def book_type_check
    allowed_book_type=["drama","scince","action","learning","fun"]
    if allowed_book_type.exclude?(book_type.downcase)
      errors.add(:book_type, "book type not ecpected")
    end
  end

  def book_pages
    if pages < 100 || pages > 1000
      errors.add(:pages,'pages should be between 100 and 1000')
    end
  end

  def us_author?
    author_country == "us"
  end


  def book_author_type
    "#{author} #{book_type}"
  end

  def reader_age
    "#{book_type} is for age over 18"
  end

  def hours_ago
    hours_diff = ((Time.now - created_at) / 1.hour).to_i
    "#{hours_diff} hours ago"
  end

  def time_ago
    total_seconds = (Time.now - created_at).to_i
    hours = total_seconds / 3600
    minutes = (total_seconds % 3600) / 60
    seconds = total_seconds % 60

    "#{hours}h #{minutes}m #{seconds}s ago"
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show,:edit,:destroy,:update]
  def index
    @books=current_user.books
  end

  def show
  end

  def destroy
    @book.destroy

    redirect_to books_path
  end

  def new
    @book=Book.new
  end

  def create
    @book=current_user.books.new(book_params)
    
    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      flash.now[:alert] = "There were errors in your submission."
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      error_message
      render :edit
    end
  end


  private

  def find_book
    @book=Book.find(params[:id])
  end


  def book_params
    params.require(:book).permit(:title, :description, :pages, :book_type ,:author_country,:user_id)
  end


  def error_message
    flash.now[:alert] = "There were errors in your submission."
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
end

app/views/books/edit.html.erb
<h1>Update Book</h1>

<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :descrition %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :author_country %>
    <%= form.text_field :author_country %>
  </div>

  <div>
    <%= form.label :pages %>
    <%= form.text_field :pages %>
  </div>


  <div>
    <%= form.label :book_type %>
    <%= form.text_field :book_type %>
  </div>

  <div>
    <%= form.submit "Updtae a Book" %>
  </div>
<% end %>


<%= button_to 'cancel' , books_path, method: :get%>

app/views/books/index.html.erb
<% if user_signed_in? %>
  Welcome: <%= current_user.first_name %>
<% end %>

<div style="margin-bottom: 50px;">
  <%= button_to 'Create a New Book', new_book_path, method: :get, class: 'btn btn-primary' %>
 
</div>

<div class="books-container">
  <% @books.each do |book| %>
    <div class="card-body">
      <p><strong>Book Name:</strong> <%= book.title %></p>
      <div class="book-actions">
      <%= link_to 'View Details', book_path(book), class: 'btn btn-info' %>
      <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning' %>
      <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div><br>
  </div><br><br>
<% end %>

</div><br>
<% if user_signed_in? %>
 <%= button_to 'My Favorites Books', favorites_path, method: :get, class: 'btn btn-primary' %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
<% end %>
</div>

app/views/books/new.html.erb
<h1>Create Book</h1>

<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :descrition %>
    <%= form.text_field :description %>
  </div>


  <div>
    <%= form.label :author_country %>
    <%= form.text_field :author_country %>
  </div>

  <div>
    <%= form.label :pages %>
    <%= form.text_field :pages %>
  </div>


  <div>
    <%= form.label :book_type %>
    <%= form.text_field :book_type %>
  </div>

  <div>
    <%= form.submit "Create a Book" %>
  </div>
<% end %>


<%= button_to 'cancel' , books_path, method: :get%>

app/views/books/show.html.erb
<div class="card shadow">
    <div class="card-header bg-primary text-white text-center">
      <h3>Book Details</h3>
      <p><strong>Author Name:</strong> <%= @book.user.full_name || 'Unknown Author' %></p>
    </div>
</div>

<%# <div class="books-container"> %>
<%=link_to ('user email'),users_path %><br>
<%= link_to ('linkedin_profil'), "https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/learn/lecture/3850390?start=1#content", target: '_blank' %>
<i class="fa-brands fa-linkedin"></i>
<div class="card-body">
          <p><strong>Book Title:</strong> Reading</p>
          <p><strong>Description:</strong> dvhjdv</p>
          <p><strong>Book Type:</strong> Drama</p>
          <p><strong>Author Country:</strong> US</p>
        </div>
<br><br><%= link_to image_tag("images.png", alt:"back",width:50,height:30),books_path%><br><br>

<% if user_signed_in? %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
<% end %>