config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about", to: "pages#about"
  get "/about_me", to: "pages#about_me"

  get "/my_car" , to: "cars#my_car"
  get "/my_car_modle" , to: "cars#car_modle"
  get "/the_color" , to: "cars#car_color"
  get "/race_car"  ,to: "cars#car_kinde"
  get "/suv_car"  ,to: "cars#suv"
  get "/coop"  ,to: "cars#coop_car"
  get "/edit" ,to: "pages#edit_each"
  get "/info" ,to: "pages#info_page"
  get "/sign_in" ,to: "pages#sign_in"

  devise_for :users

  resources :users
  resources :books
  resources :favorites

  post "/add_book_to_favorites", to: "favorites#create"
  delete "/remove_book_from_favorites", to: "favorites#destroy"

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def my_car
  end

  def car_modle
  end

  def car_color
    @car_color="red"
  end

  def car_kinde
    @speedy_car="bagatti"
  end

  def suv
  end

  def coop_car
  end

end

app/views/cars/car_color.html.erb
<%= button_to 'go to about me' , about_me_path , method: :get%>

<%= button_to 'go to about' , about_path , method: :get%>

<%= button_to 'go back home' , root_path , method: :get%>

<%= button_to 'go to my_car' , my_car_path , method: :get%>


<%=@car_color%>

<%= button_to 'go to car modle' , my_car_modle_path , method: :get%>

app/views/cars/car_kinde.html.erb
<%=@speedy_car%>

<img src="https://www.bugatti.com/media/pcsffbw3/gallery7.png?cc=0,0.1060445287080252,0,0.15255570853989892&amp;width=1920&amp;height=900&amp;rnd=133343651602600000" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1920px; height: 149px; margin: 0px; width: 318px;" alt="https://www.bugatti.com/media/pcsffbw3/gallery7.png?cc=0,0.1060445287080252,0,0.15255570853989892&amp;width=1920&amp;height=900&amp;rnd=133343651602600000" jsname="kn3ccd" aria-hidden="false">

app/views/cars/car_modle.html.erb
<%= button_to 'go to about me' , about_me_path , method: :get%>

<%= button_to 'go to about' , about_path , method: :get%>

<%= button_to 'go back home' , root_path , method: :get%>

<%= button_to 'go to my_car' , my_car_path , method: :get%>






<%= button_to 'go back home' , root_path , method: :get%>

the modle is tyota


<%= button_to 'go to car color' , the_color_path , method: :get%>

app/views/cars/coop_car.html.erb
<img src="https://preview.redd.it/what-car-is-coop-driving-v0-5s6uc2e804uc1.png?auto=webp&amp;s=ecc396dfbec4a2257e7be347905c00ec6b13b234" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1920px; width: 288px; height: 207px; margin: 0px;" alt="What car is coop driving? : r/whatisthiscar" jsname="kn3ccd" aria-hidden="false">

app/views/cars/my_car.html.erb
<%= button_to 'go to about me' , about_me_path , method: :get%>

<%= button_to 'go to about' , about_path , method: :get%>

<%= button_to 'go back home' , root_path , method: :get%>


<%= button_to 'go to car modle' , my_car_modle_path , method: :get%>

<%= button_to 'go back home' , root_path , method: :get%>



this is my car page

app/views/cars/suv.html.erb
<img src="https://www.hyundainews.com/assets/images/original/44400-HyundaiSUVlineupFinal.jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1200px; width: 363px; height: 242px; margin: 0px;" alt="Hyundai Named 2021 Best SUV Brand by U.S. News &amp; World ..." jsname="kn3ccd" aria-hidden="false">